### ISSUE TITLE
open_git depends on photo_view ^0.4.2, version solving failed.

### ISSUE THREAD

**Issue by puretsang** [Yuzopro/OpenGit_Flutter#3]
刚clone 下来 flutter packages get 报错
The current Flutter SDK version is 1.5.4-hotfix.2.                      
                                                                        
Because photo_view 0.4.2 requires Flutter SDK version >=1.5.9-pre.94 <2.0.0 and no versions of photo_view match >0.4.2 <0.5.0, photo_view ^0.4.2 is forbidden.
So, because open_git depends on photo_view ^0.4.2, version solving failed.
Running "flutter packages get" in opengit_flutter...                    
pub get failed (1)

**Comment by Yuzopro** [comment]
执行下flutter doctor看下flutter SDK的版本是多少

**Comment by puretsang** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by Yuzopro** [comment]
photo_view 0.4.2 requires Flutter SDK version >=1.5.9-pre.94 <2.0.0。你现在的版本是v1.5.4-hotfix.2，执行下flutter upgrade

**Comment by puretsang** [comment]
> photo_view 0.4.2 requires Flutter SDK version >=1.5.9-pre.94 <2.0.0。你现在的版本是v1.5.4-hotfix.2，执行下flutter upgrade

clear!! 3Q
