### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by DavidMGT** [Yuzopro/OpenGit_Flutter#4]
Because open_git depends on install_apk_plugin from path which doesn't exist (could not find package install_apk_plugin at "flutter_common_lib/install_apk_plugin"), version solving failed.

pub get failed (66)

**Comment by Yuzopro** [comment]
是这样操作的吗？
//clone
git clone --recursive https://github.com/Yuzopro/opengit_flutter.git 
git checkout -b master origin/master 
cd flutter_common_lib 
git checkout -b master origin/master
//运行
cd ../
flutter build apk
flutter install
